### ISSUE TITLE
Problem Set Problem

### ISSUE THREAD

**Issue by riskeay** [SmithLinux/MIT6.031-software-construction#1]
I have a problem to clone the problem set from this code
![image](https://user-images.githubusercontent.com/95848505/227884125-c2414fbb-3d3b-4b01-82ef-a6804acd9a9f.png)

Can you point a right road for me?

**Comment by SmithLinux** [comment]
Hi,
 this course is from MIT OpenCourseWare:
 https://ocw.mit.edu/courses/6-005-software-construction-spring-2016/

**Comment by SmithLinux** [comment]
> I have a problem to clone the problem set from this code ![image](https://user-images.githubusercontent.com/95848505/227884125-c2414fbb-3d3b-4b01-82ef-a6804acd9a9f.png)
> 
> Can you point a right road for me?

Hi,
this course is from MIT OpenCourseWare:
https://ocw.mit.edu/courses/6-005-software-construction-spring-2016/
